/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Pratica_04_Praticando_02;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
